# Generated by Django 6.1 on 2026-09-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='nome_completo',
            field=models.CharField(default='Usuário Desconhecido', max_length=100, unique=True),
        ),
    ]
