# Generated by Django 6.1 on 2026-09-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_register', '0002_usuarios_nome_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='username',
        ),
    ]
